# Generated by Django 4.2.19 on 2025-02-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_business_profile_pic_freelancer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
