# Generated by Django 4.2.19 on 2025-02-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_freelancer_latitude_freelancer_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('demand_count', models.IntegerField(default=0)),
            ],
        ),
    ]
